# Generated by Django 5.0.4 on 2024-04-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DedicateServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_zip', models.FileField(upload_to='server', verbose_name='dedicate server')),
            ],
        ),
    ]
